######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 27 18:34:55 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interface_control.h
FORMS += interface_control.ui
SOURCES += interface_control.cpp main.cpp
LIBS += -lwiringPi
